server:
  port: 8081

spring:
  profiles:
    include: security

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    com.demo: debug
    org.hibernate.type.descriptor.sql: trace